In [1]:
import refinitiv.data as rd
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import yfinance as yf

In [29]:
rd.open_session()

In [37]:
tickers = [
    "ASML.AS",
    "MC.PA",
    "SAN.PA",
    "AIR.PA",
    "SU.PA",
    "OR.PA",
    "BNP.PA",
    "RMS.PA",
    "DG.PA",
    "ADS.DE"
]

In [40]:
data = []
for t in tickers: 
    info = yf.Ticker(t).info
    data.append({
        "Ticker": t,
        "Name": info.get("longName"),
        "Sector": info.get("sector"),
        "Industry": info.get("industry")
    })

df_meta = pd.DataFrame(data)
print(df_meta)
df_meta.to_excel("company_info.xlsx", index=False)

    Ticker                                               Name  \
0  ASML.AS                                  ASML Holding N.V.
1    MC.PA  LVMH Moët Hennessy - Louis Vuitton, Société Eu...
2   SAN.PA                                             Sanofi
3   AIR.PA                                          Airbus SE
4    SU.PA                            Schneider Electric S.E.
5    OR.PA                                       L'Oréal S.A.
6   BNP.PA                                     BNP Paribas SA
7   RMS.PA  Hermès International Société en commandite par...
8    DG.PA                                           Vinci SA
9   ADS.DE                                          adidas AG

               Sector                             Industry
0          Technology  Semiconductor Equipment & Materials
1   Consumer Cyclical                         Luxury Goods
2          Healthcare         Drug Manufacturers - General
3         Industrials                  Aerospace & Defense
4         Industrials       Specialty Industrial Machinery
5  Consumer Defensive        Household & Personal Products
6  Financial Services                     Banks - Regional
7   Consumer Cyclical                         Luxury Goods
8         Industrials           Engineering & Construction
9   Consumer Cyclical               Footwear & Accessories

In [39]:
end = datetime.today()
start = end - timedelta(days=365)

### Get historical price data for the selected stocks

In [ ]:
prices = yf.download(
    tickers,
    start="2022-01-01",
    end="2026-01-01"
)["Close"]

[*********************100%***********************]  10 of 10 completed

In [43]:
prices.head()

Ticker,ADS.DE,AIR.PA,ASML.AS,BNP.PA,DG.PA,MC.PA,OR.PA,RMS.PA,SAN.PA,SU.PA
Date,,,,,,,,,,
2022-01-03,250.221085,108.519745,673.338379,45.376587,79.531700,677.224121,400.595062,1486.069214,76.128380,162.377914
2022-01-04,249.641632,111.079964,653.762878,46.896557,81.290871,689.267822,405.673035,1501.965576,75.054588,164.565948
2022-01-05,251.911118,112.500237,643.783264,46.955872,81.059166,702.237854,402.663879,1520.752197,75.225037,164.862656
2022-01-06,244.088669,110.855705,631.884399,47.593517,80.887550,673.611023,388.370331,1449.459351,75.114250,159.503799
2022-01-07,238.970291,109.977386,638.025757,47.823364,80.707344,663.142334,385.126038,1394.063232,75.506264,157.056183

### Analysis the data

In [44]:
returns = np.log(prices/prices.shift(1)).dropna()
returns.head()

Ticker,ADS.DE,AIR.PA,ASML.AS,BNP.PA,DG.PA,MC.PA,OR.PA,RMS.PA,SAN.PA,SU.PA
Date,,,,,,,,,,
2022-01-04,-0.002318,0.023318,-0.029503,0.032948,0.021878,0.017628,0.012596,0.010640,-0.014205,0.013385
2022-01-05,0.009050,0.012705,-0.015383,0.001264,-0.002854,0.018642,-0.007445,0.012430,0.002268,0.001801
2022-01-06,-0.031545,-0.014726,-0.018656,0.013488,-0.002119,-0.041619,-0.036143,-0.048014,-0.001474,-0.033045
2022-01-07,-0.021192,-0.007955,0.009672,0.004818,-0.002230,-0.015663,-0.008389,-0.038968,0.005205,-0.015464
2022-01-10,-0.013016,0.001867,-0.066214,-0.007782,0.003291,-0.018471,-0.037060,-0.051766,0.002818,-0.052724

In [45]:
cov_matrix = returns.cov() * 252